### ISSUE TITLE
Docker file improvements

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-index#14]
via @alexgleith :

```
Pedantic: dockerfile should be Dockerfile
For the requirements, copying all three requirements files in at once would be better, and then running the pip installs in a single RUN command will be much better.
It doesn't need the Environment can be whaterver... section.
The COPY of the update_ranges etc should probably go into /usr/local/bin/ so that they can be called without the path... I think that'll be nice :slightly_smiling_face: . Ideally they'll not be dodgy wrappers too.
```

_Originally posted by @whatnick in https://github.com/opendatacube/datacube-index/pull/13#issuecomment-605727362_

**Comment by whatnick** [comment]
@alexgleith In my approach due to special issues with `aiobotocore`  we will be using 3x containers with a DAG tying them together. This repo will build into an S3->ODC container with standard OWS and Explorer containers following it up with standard scripts to publish the newly indexed data into those applications downstream.

**Comment by alexgleith** [comment]
Sounds good to me :-) 

Not sure why there's `aibotocore` issues, though. What is the issue?
