### ISSUE TITLE
Datacube Bootstrap Script from metadata/product catalog

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-index#46]
Create a CLI tool to Bootstrap a fresh datacube from a CSV of products and their definitions and a master YAML of all the metadata definitions. This is designed to be a Python script, currently exists as a bash script.

```
############################################################
# This script allows creation of all products in an ODC    #
# instance from a given CSV catalog definition             #
# In local development activate <odc> conda environment    #
# In kubernetes pod executor run <datacube-core> container #
############################################################
product_catalog = $1
metadata_catalog = $2

datacube system init --no-default-types --no-init-users
# Created using : datacube metadata list | awk '{print $1}' | xargs datacube metadata show
datacube metadata add $metadata_catalog
wget $product_catalog -O product_list.csv
cat product_list.csv | tail -n+2 | awk -F, '{print $2}' | xargs datacube -v product add
```

**Comment by uchchwhash** [comment]
Our previous attempt at this: [dea-system init](https://github.com/GeoscienceAustralia/digitalearthau/blob/9ccaa08643efdd815a3e5a5f952cb8aac7b230b0/digitalearthau/system.py#L29)

Hope I am not misunderstanding/misrepresenting the problem being addressed here.

**Comment by whatnick** [comment]
This would address the same issue but would be less filesystem based and support URL's to allow usage with git sensors in airflow in more GitOps manner.
